name: Update README with Weekly Study Logs

on:
  schedule:
    - cron: '0 0 * * *'  # 매일 자정 실행 (UTC 기준)
  workflow_dispatch: # 수동 실행도 가능

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    # 1. 레포지토리 클론
    - name: Checkout Repository
      uses: actions/checkout@v3

    # 2. Python 설치
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9' # 필요한 Python 버전

    # 3. 종속성 설치 (필요한 경우)
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        # 필요한 패키지 설치 (현재는 없음)

    # 4. Python 스크립트 실행
    - name: Run Python Script
      run: |
        python update_readme.py

    # 5. 변경 사항 커밋 및 푸시
    - name: Commit and Push Changes
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add README.md *.svg  # SVG 파일 추가
        git commit -m "Update README with weekly study logs and SVG charts"
        git push
